riddles = [
    {"question": "What has keys but can’t open locks?", "answer": "piano", "hint": "It makes music."},
    {"question": "I speak without a mouth and hear without ears. What am I?", "answer": "echo", "hint": "You shout and it replies."},
    {"question": "What can travel around the world while staying in the corner?", "answer": "stamp", "hint": "It's on an envelope."},
    {"question": "The more you take, the more you leave behind. What are they?", "answer": "footsteps", "hint": "You leave them on sand or snow."},
    {"question": "What has hands but can’t clap?", "answer": "clock", "hint": "It tells time."},
    {"question": "What runs but never walks?", "answer": "water", "hint": "Found in rivers."},
    {"question": "I have cities but no houses. What am I?", "answer": "map", "hint": "It fits in your pocket."},
    {"question": "What gets wetter the more it dries?", "answer": "towel", "hint": "Used after a shower."},
    {"question": "What has a head and a tail but no body?", "answer": "coin", "hint": "Flip it to make a decision."},
    {"question": "What goes up but never comes down?", "answer": "age", "hint": "It's just a number."},
    {"question": "What is full of holes but still holds water?", "answer": "sponge", "hint": "It’s used for washing."},
    {"question": "What belongs to you but others use it more?", "answer": "name", "hint": "It’s how people call you."},
    {"question": "What has a neck but no head?", "answer": "bottle", "hint": "Often holds water or juice."},
    {"question": "What comes once in a minute, twice in a moment, but never in a thousand years?", "answer": "m", "hint": "It’s a letter."},
    {"question": "What’s always in front of you but can’t be seen?", "answer": "future", "hint": "It hasn't happened yet."},
    {"question": "What breaks yet never falls, and what falls yet never breaks?", "answer": "day and night", "hint": "They divide the day."},
    {"question": "I’m tall when I’m young, and short when I’m old. What am I?", "answer": "candle", "hint": "It melts down."},
    {"question": "What can you catch but not throw?", "answer": "cold", "hint": "You sneeze with it."},
    {"question": "What comes down but never goes up?", "answer": "rain", "hint": "It pours from clouds."},
    {"question": "If you drop me I’m sure to crack, but give me a smile and I’ll always smile back. What am I?", "answer": "mirror", "hint": "It reflects."},
    {"question": "What has one eye but can’t see?", "answer": "needle", "hint": "Used for sewing."},
]
