riddles = [
    {"question": "What has keys but can’t open locks?", "answer": "piano"},
    {"question": "I speak without a mouth and hear without ears. What am I?", "answer": "echo"},
    {"question": "What can travel around the world while staying in the corner?", "answer": "stamp"},
    {"question": "The more you take, the more you leave behind. What are they?", "answer": "footsteps"},
    {"question": "What has hands but can’t clap?", "answer": "clock"},
    {"question": "What runs but never walks?", "answer": "water"},
    {"question": "I have cities but no houses. What am I?", "answer": "map"},
    {"question": "What gets wetter the more it dries?", "answer": "towel"},
    {"question": "What has a head and a tail but no body?", "answer": "coin"},
    {"question": "What goes up but never comes down?", "answer": "age"},
    {"question": "What is full of holes but still holds water?", "answer": "sponge"},
    {"question": "What belongs to you but others use it more?", "answer": "name"},
    {"question": "What has a neck but no head?", "answer": "bottle"},
    {"question": "What comes once in a minute, twice in a moment, but never in a thousand years?", "answer": "m"},
    {"question": "What’s always in front of you but can’t be seen?", "answer": "future"},
    {"question": "What breaks yet never falls, and what falls yet never breaks?", "answer": "day and night"},
    {"question": "I’m tall when I’m young, and short when I’m old. What am I?", "answer": "candle"},
    {"question": "What can you catch but not throw?", "answer": "cold"},
    {"question": "What comes down but never goes up?", "answer": "rain"},
    {"question": "If you drop me I’m sure to crack, but give me a smile and I’ll always smile back. What am I?", "answer": "mirror"},
    {"question": "What has one eye but can’t see?", "answer": "needle"},
]
